/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package httpServer_sample;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Map.Entry;

public class Library {
	public static void main(String[] args) throws Exception {
		System.out.println("start server >>>");

		try (
				ServerSocket server = new ServerSocket(80);
				Socket socket = server.accept();
				BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream(), "UTF-8"));
				BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));) {

			Request request = new Request(in);
			System.out.println(request.get1stLine());
			for (Entry<String, String> entry : request.getHeaders().entrySet()) {
				System.out.println(entry.getKey() + "：" + entry.getValue());
			}
			System.out.println();
			System.out.println(request.getBody());

			Response response = new Response(request);

			bw.write(response.get1stLine() + "\n");
			for (Entry<String, String> entry : response.getHeaders().entrySet()) {
				bw.write(entry.getKey() + "：" + entry.getValue() + "\n");
			}
			bw.write("\n");
			bw.write(response.getBody());
			bw.flush();

		}

		System.out.println("<<< end server");
	}

}
