/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package httpServer_sample;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;


public class Library {
    public static void main(String[] args) throws Exception {
        System.out.println("start server >>>");

        try(
        	ServerSocket server = new ServerSocket(80);
        	Socket socket = server.accept();
        	BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream(),"UTF-8"));
        	BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
        	){

        	String line = in.readLine();
        	StringBuilder header = new StringBuilder();
        	int contentLength = 0;

        	while (line != null && !line.isEmpty()) {
        		if (line.startsWith("Content-Length")) {
                    contentLength = Integer.parseInt(line.split(":")[1].trim());
                }
        		header.append(line + "\n");
                line = in.readLine();
        	}

        	String body = "";

        	if(contentLength > 0) {
        		char[] b = new char[contentLength];
        		in.read(b,0,contentLength);
        		body = new String(b);
        	}

        	System.out.println(header);
        	System.out.println(body);

        	bw.write("HTTP/1.1 200 OK" + "\n" +
        			"Content-Type: text/html" + "\n" + "\n" +
        			"<h1>Hello World!!</h1>\n");
            bw.flush();
        }

        System.out.println("<<< end server");
    }
}
